name: Testing and linting

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Testing and linting
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12, 14]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup CI environment for ${{ matrix.node-version }}
        run: make install ENV=ci  

      - run: make lint DOCKER=false
        if: ${{ always() }}
  
      - run: make test_unit DOCKER=false
        if: ${{ always() }}
    
      - run: make test_integration DOCKER=false
        if: ${{ always() }}